apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pgdb

spec:
  type: bindings.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=postgresrvlgazuredays.postgres.database.azure.com user=azuredays password=ADays_2024! port=5432 connect_timeout=10 database=daprdb"
